### ISSUE TITLE
Tag a 1.0.0 release

### ISSUE THREAD

**Issue by kyleconroy** [shurcooL/sanitized_anchor_name#4]
[dep](https://github.com/golang/dep), the official experiment in Golang packaging, released it's first stable version last month. dep expects projects to have tagged releases on Github. Could you tag a 1.0.0 release for this repository? Thanks

**Comment by dmitshur** [comment]
Sure, I can do that.

I'd like to understand this better, can you tell me more about what are the ways your user experience with `dep` is worse when this package does not have any releases? How would it be improved once I add a `v1.0.0` tag?

**Comment by kyleconroy** [comment]
Sure, here's a concrete example. My `Gopkg.lock` file currently looks like this:

```toml
[[projects]]
  name = "github.com/russross/blackfriday"
  packages = ["."]
  revision = "cadec560ec52d93835bf2f15bd794700d3a2473b"
  version = "v2.0.0"

[[projects]]
  branch = "master"
  name = "github.com/shurcooL/sanitized_anchor_name"
  packages = ["."]
  revision = "541ff5ee47f1dddf6a5281af78307d921524bcb5"
```

For `sanitized_anchor_name`, it points to your master branch. In the future, if you ever decide to make a breaking change, updating my dependencies will also cause my code to break. If you instead tag a v1.0.0 tag, I can be sure that I won't accidentally take in new changes.
